version: '3.4'

services:
  node:
    build:
      context: .
      dockerfile: ./containers/node/Dockerfile
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    networks:
      - db-network
    env_file: ./containers/node/env
    ports:
      - 5161:5161
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
    networks:
      - db-network

volumes:
  db-data:

networks:
  db-network:
    driver: bridge
